- name: DNF mysql installation
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start the backend service
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: yes

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Check the DB connection with our password
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1 
    #"{{mysql_root_password}}"
    login_host: localhost
    #mysql-dev.rdevops6a.online
    filter: version
  register: mysql_connection_output
  ignore_errors: yes'

- name: print
  debug:
    msg:"{{mysql_connection_output}}"

- name: start the backend service
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseAp